### PR TITLE
fix: App Crash

### LINKED ISSUE #48: App crash
When the difficulty is set to hard and category to politics, arts, celebrities, ... the app crashes. When checked the API the response code is 1. So this means there are not enough questions. So the questions have to be reduced based on that.
Can get the number of questions present through the URL
_https://opentdb.com/api_count.php?category=CATEGORY_ID_HERE_

### PR DESCRIPTION
**Pull request by Miftahunajat**
Fixes #48 App Crash

Changes: Add Count Quiz First

### CODE REVIEW

File: app/src/main/java/com/example/immadisairaj/quiz/api/ApiCount.java [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+	public void setCategoryQuestionCount(CategoryQuestionCount categoryQuestionCount){
+		this.categoryQuestionCount = categoryQuestionCount;
+	}
+
+	public CategoryQuestionCount getCategoryQuestionCount(){
+		return categoryQuestionCount;
+	}
+
+	@Override
+ 	public String toString(){
```
Comment (immadisairaj) [inline app/src/main/java/com/example/immadisairaj/quiz/api/ApiCount.java]: can you remove this method?
or add this method in the other two classes.
Because we have to follow the same format everywhere.

File: app/src/main/java/com/example/immadisairaj/quiz/api/CategoryQuestionCount.java [hunk 2]
```diff
@@ -0,0 +1,61 @@
...
+	public void setTotalQuestionCount(int totalQuestionCount){
+		this.totalQuestionCount = totalQuestionCount;
+	}
+
+	public int getTotalQuestionCount(){
+		return totalQuestionCount;
+	}
+
+	@Override
+ 	public String toString(){
```
Comment (immadisairaj) [inline app/src/main/java/com/example/immadisairaj/quiz/api/CategoryQuestionCount.java]: same as above

**Review by immadisairaj — CHANGES_REQUESTED** [review]

**Comment by immadisairaj** [comment]
Can you change the title of the PR to semantic.

You can refer [this](https://github.com/commitizen/conventional-commit-types/blob/master/index.json).

File: app/src/main/java/com/example/immadisairaj/quiz/api/ApiCount.java (hunk 1 above)
Comment (Miftahunajat) [reply app/src/main/java/com/example/immadisairaj/quiz/api/ApiCount.java]: Thank you i already updated it in my local remote. But it seems this pull request not updated

Comment (Miftahunajat) [reply app/src/main/java/com/example/immadisairaj/quiz/api/ApiCount.java]: I already updated it

File: app/src/main/java/com/example/immadisairaj/quiz/api/CategoryQuestionCount.java (hunk 2 above)
Comment (Miftahunajat) [reply app/src/main/java/com/example/immadisairaj/quiz/api/CategoryQuestionCount.java]: Already updated it

**Review by immadisairaj — APPROVED** [review]
Thanks for the PR 👍
